

# This file was *autogenerated* from the file /mnt/c/Users/flocto/Documents/Cybersecurity/2024/lactf/shuffler/test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_617 = Integer(617)
def factor(x):
    return [i for i in range(_sage_const_1 , x+_sage_const_1 ) if x % i == _sage_const_0 ]
vals = []
for i in range(_sage_const_1 , _sage_const_617 ):
    facs = factor(i)
    print(i, facs)
    vals.append((i, len(facs)))

vals = sorted(vals, key=lambda x: x[_sage_const_1 ])
vals = [v for v in vals if v[_sage_const_1 ] == vals[-_sage_const_1 ][_sage_const_1 ]]
print(vals)

