

# This file was *autogenerated* from the file hmm.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2760624790958533 = Integer(2760624790958533); _sage_const_4164880461924199 = Integer(4164880461924199); _sage_const_52 = Integer(52); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2)
import itertools
def small_roots(f, bounds, m=_sage_const_1 , d=None):
	if not d:
		d = f.degree()

	if isinstance(f, Polynomial):
		x, = polygens(f.base_ring(), f.variable_name(), _sage_const_1 )
		f = f(x)

	R = f.base_ring()
	N = R.cardinality()
	
	f /= f.coefficients().pop(_sage_const_0 )
	f = f.change_ring(ZZ)

	G = Sequence([], f.parent())
	for i in range(m+_sage_const_1 ):
		base = N**(m-i) * f**i
		for shifts in itertools.product(range(d), repeat=f.nvariables()):
			g = base * prod(map(power, f.variables(), shifts))
			G.append(g)

	B, monomials = G.coefficient_matrix()
	monomials = vector(monomials)

	factors = [monomial(*bounds) for monomial in monomials]
	for i, factor in enumerate(factors):
		B.rescale_col(i, factor)

	B = B.dense_matrix().LLL()

	B = B.change_ring(QQ)
	for i, factor in enumerate(factors):
		B.rescale_col(i, _sage_const_1 /factor)

	H = Sequence([], f.parent().change_ring(QQ))
	for h in filter(None, B*monomials):
		H.append(h)
		I = H.ideal()
		if I.dimension() == -_sage_const_1 :
			H.pop()
		elif I.dimension() == _sage_const_0 :
			roots = []
			for root in I.variety(ring=ZZ):
				root = tuple(R(root[var]) for var in f.variables())
				roots.append(root)
			return roots

	return []

a = _sage_const_2760624790958533 
c = _sage_const_4164880461924199 
m = _sage_const_1  << _sage_const_52 
a_inv = pow(a, -_sage_const_1 , m)

F = Integers(m)

low = F(floor(m/_sage_const_10 *_sage_const_9 ))

P = PolynomialRing(F, names=('x', 'y',)); (x, y,) = P._first_ngens(2)

lhs = -x
for _ in range(_sage_const_8 ):
    lhs = a*lhs + c

rhs = -y
for _ in range(_sage_const_8 ):
    rhs = a_inv*(rhs - c)

f = lhs - rhs
print(f)

roots = small_roots(f, [low]*_sage_const_2 , _sage_const_2 )

