[package]
name = "corbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
