; enable supervisorctl socket
[unix_http_server]
file=/tmp/supervisor.sock        ; path to socket file
chmod=0770                       ; socket permissions
chown=root:editor                 ; default is no owner

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[supervisord]
user=root
nodaemon=true
stderr_logfile=/dev/null
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g 'daemon off;'
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:app]
command=java -jar app.jar  -Djava.security.manager -Djava.security.policy==/opt/no-exec.policy
user=challenger
directory=/app/java
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0


;[program:editor]
;command=python3 app.py
;user=editor
;directory=/app/backend
;autostart=true
;autorestart=true
;stdout_logfile=/dev/stdout
;stderr_logfile=/dev/stderr
;stdout_logfile_maxbytes=0
;stderr_logfile_maxbytes=0