

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_31179 = Integer(31179); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_171687271187362402858253153317226779412519708415758861260173615154794651529095285554559087769129718750696204276854381696836947720354758929262422945910586370154930700427498878225153794722572909742395687687136063410003254320613429926120729809300639276228416026933793038009939497928563523775713932771366072739767 = Integer(171687271187362402858253153317226779412519708415758861260173615154794651529095285554559087769129718750696204276854381696836947720354758929262422945910586370154930700427498878225153794722572909742395687687136063410003254320613429926120729809300639276228416026933793038009939497928563523775713932771366072739767); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8)
from pwn import remote
import itertools
# nc chall.lac.tf 31179
r = remote('chall.lac.tf', int(_sage_const_31179 ))

def small_roots(f, bounds, m=_sage_const_1 , d=None):
    if not d:
        d = f.degree()

    if isinstance(f, Polynomial):
        x, = polygens(f.base_ring(), f.variable_name(), _sage_const_1 )
        f = f(x)

    R = f.base_ring()
    N = R.cardinality()
    
    f /= f.coefficients().pop(_sage_const_0 )
    f = f.change_ring(ZZ)

    G = Sequence([], f.parent())
    for i in range(m+_sage_const_1 ):
        base = N**(m-i) * f**i
        for shifts in itertools.product(range(d), repeat=f.nvariables()):
            g = base * prod(map(power, f.variables(), shifts))
            G.append(g)

    B, monomials = G.coefficient_matrix()
    monomials = vector(monomials)

    factors = [monomial(*bounds) for monomial in monomials]
    for i, factor in enumerate(factors):
        B.rescale_col(i, factor)

    B = B.dense_matrix().LLL()

    B = B.change_ring(QQ)
    for i, factor in enumerate(factors):
        B.rescale_col(i, _sage_const_1 /factor)

    H = Sequence([], f.parent().change_ring(QQ))
    for h in filter(None, B*monomials):
        H.append(h)
        I = H.ideal()
        if I.dimension() == -_sage_const_1 :
            H.pop()
        elif I.dimension() == _sage_const_0 :
            roots = []
            for root in I.variety(ring=ZZ):
                root = tuple(R(root[var]) for var in f.variables())
                roots.append(root)
            return roots

    return []

p = _sage_const_171687271187362402858253153317226779412519708415758861260173615154794651529095285554559087769129718750696204276854381696836947720354758929262422945910586370154930700427498878225153794722572909742395687687136063410003254320613429926120729809300639276228416026933793038009939497928563523775713932771366072739767 
P = GF(p)
PP = PolynomialRing(P, names=('s',)); (s,) = PP._first_ngens(1)

r.recvline()
s_pow = eval(r.recvline().decode().split(': ')[_sage_const_1 ])
alpha_pow = eval(r.recvline().decode().split(': ')[_sage_const_1 ])
print(s_pow)
print(alpha_pow)

r.recvline()
coefs = eval(r.recvline().decode().split(': ')[_sage_const_1 ])

for _ in range(_sage_const_3 ):
    r.sendlineafter(b'> ', b'2')

target = eval(r.recvline().decode().split('was ')[_sage_const_1 ])

print(f"target: {target}")

f = sum([coefs[i] * s**(_sage_const_7  - i) for i in range(_sage_const_8 )])
f = f - target
f = f.monic()
print(f"monic: {f}")
rts = f.roots()
print(f'roots: {r}')
s = rts[-_sage_const_1 ][_sage_const_0 ]
print(s)

assert sum(coefs[i] * pow(s, _sage_const_7 -i, p) for i in range(_sage_const_8 )) %p == target

coefs = eval(r.recvline_contains(b'target polynomial: ').decode().split(': ')[_sage_const_1 ])
# print(coefs)

ts = int(sum(coefs[i] * pow(s, _sage_const_7 -i, p) for i in range(_sage_const_8 )) % p )
print(f"ts: {ts}")

d = pow(ts, -_sage_const_1 , p-_sage_const_1 )
print(f"d: {d}")
for f, fa in zip(s_pow, alpha_pow):
    try:
        h = pow(int(f), int(d), int(p))
        print(f"h: {h}")
        print(f"f: {f}")
        assert pow(h, int(ts), int(p)) == f
        
        r.sendlineafter(b'> ', str(f).encode())
        r.sendlineafter(b'> ', str(h).encode())
        r.sendlineafter(b'> ', str(fa).encode())
        break
    except Exception as e:
        print(e)
        pass

r.interactive()


